# Generated by Django 4.2.6 on 2023-10-19 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 19, 2, 55, 22, 906673, tzinfo=datetime.timezone.utc)),
        ),
    ]
